docs: improve hosting overview
unoplatform/uno.extensions pull request #1259
Opened 2023-03-13 00:46 UTC by lukeblevins

GitHub Issue (If applicable): #1198 

## PR Type

What kind of change does this PR introduce?
- Documentation content changes

## What is the current behavior?

## What is the new behavior?

## PR Checklist

Please check if your PR fulfills the following requirements:

- [ ] Tested code with current [supported SDKs](../README.md#supported)
- [ ] Docs have been added/updated which fit [documentation template](https://github.com/nventive/Uno/blob/master/doc/.feature-template.md). (for bug fixes / features)
- [ ] [Unit Tests and/or UI Tests](doc/articles/working-with-the-samples-apps.md) for the changes have been added (for bug fixes / features) (if applicable)
- [ ] [Wasm UI Tests](doc/articles/working-with-the-samples-apps.md#running-the-webassembly-ui-tests-snapshots) are not showing unexpected any differences. Validate PR `Screenshots Compare Test Run` results.
- [ ] Contains **NO** breaking changes
- [ ] Updated the [Release Notes](https://github.com/nventive/Uno/tree/master/doc/ReleaseNotes)
- [ ] Associated with an issue (GitHub or internal)

## Other information

Internal Issue (If applicable):

2023-03-13 17:09 UTC, dansiegel requested changes
thinking this should probably be updated to include some information on the use of the IApplicationBuilder
```cs
protected override void OnLaunched(LaunchActivatedEventArgs args)
{
    var builder = this.CreateBuilder(args)
        .Configure(host => {
            // configure the host builder
        });
}
```

2023-03-16 07:22 UTC, nickrandolph commented on doc/Overview/Hosting/HostingOverview.md
> +Hosting is delivered as a NuGet package [Microsoft.Extensions.Hosting.WinUI](https://www.nuget.org/packages/Uno.Extensions.Hosting.WinUI) or [Microsoft.Extensions.Hosting.UWP](https://www.nuget.org/p
remove reference to uwp here

2023-03-16 07:23 UTC, nickrandolph approved these changes

2023-03-16 07:24 UTC, nickrandolph commented
> thinking this should probably be updated to include some information on the use of the IApplicationBuilder
> 
> ```cs
> protected override void OnLaunched(LaunchActivatedEventArgs args)
> {
>     var builder = this.CreateBuilder(args)
>         .Configure(host => {
>             // configure the host builder
>         });
> }
> ```

Good suggestion - let's push to a new PR so that we can just get existing docs updated to something that's "correct" in this pass

2023-03-16 14:40 UTC, nickrandolph approved these changes

2023-03-17 09:48 UTC, dansiegel approved these changes

2023-03-17 09:48 UTC, merged