docs: update information about testing docs
unoplatform/uno.extensions pull request #1412
Opened 2023-04-26 18:05 UTC by weitzhandler

## PR Type

- Documentation content changes
- Project automation

## PR Checklist

Please check if your PR fulfills the following requirements:

- [x] Contains **NO** breaking changes

## Other information

2023-04-27 09:15 UTC, nickrandolph requested changes
As per chat, please remove the import_external_docs_test.ps1, or at least modify it to call the existing import_external_docs.ps1 so that we don't have duplicate lists of imports.

2023-04-27 12:50 UTC, weitzhandler commented
Is import_external_docs.ps1 used for any other purposes other than testing locally?

2023-05-01 10:31 UTC, weitzhandler commented
See https://github.com/unoplatform/uno/pull/12126

2023-05-10 08:15 UTC, nickrandolph approved these changes

2023-05-10 08:16 UTC, merged