feat: Adding Validation to Uno Extensions
unoplatform/uno.extensions pull request #982
Opened 2022-12-12 05:20 UTC by nickrandolph

GitHub Issue (If applicable): #981

## PR Type

What kind of change does this PR introduce?
- Feature

## What is the current behavior?

No support for validation in extensions

## What is the new behavior?

Adds support for validation

## PR Checklist

Please check if your PR fulfills the following requirements:

- [ ] Tested code with current [supported SDKs](../README.md#supported)
- [ ] Docs have been added/updated which fit [documentation template](https://github.com/nventive/Uno/blob/master/doc/.feature-template.md). (for bug fixes / features)
- [ ] [Unit Tests and/or UI Tests](doc/articles/working-with-the-samples-apps.md) for the changes have been added (for bug fixes / features) (if applicable)
- [ ] [Wasm UI Tests](doc/articles/working-with-the-samples-apps.md#running-the-webassembly-ui-tests-snapshots) are not showing unexpected any differences. Validate PR `Screenshots Compare Test Run` results.
- [ ] Contains **NO** breaking changes
- [ ] Updated the [Release Notes](https://github.com/nventive/Uno/tree/master/doc/ReleaseNotes)
- [ ] Associated with an issue (GitHub or internal)

## Other information

Internal Issue (If applicable):

2022-12-12 15:25 UTC, dr1rrb commented on src/Uno.Extensions.Validation/IValidator.cs
> +public interface IValidator<in T>
Please see my comment on the discussion https://github.com/unoplatform/uno.extensions/discussions/324#discussioncomment-4380008 :)

2022-12-12 15:28 UTC, dr1rrb commented on src/Uno.Extensions.Validation/SystemValidator.cs
> +		return new ValueTask<IEnumerable<ValidationResult>>(results.ToList());
```suggestion
		return new ValueTask<IEnumerable<ValidationResult>>(results);
```

2022-12-12 15:36 UTC, dr1rrb commented on src/Uno.Extensions.Validation/Uno.Extensions.Validation.csproj
> +		<WarningsNotAsErrors>$(WarningsNotAsErrors);CS1591</WarningsNotAsErrors>
Remove this for new projects.

2022-12-12 15:42 UTC, dr1rrb requested changes

2022-12-12 15:42 UTC, dr1rrb commented on src/Uno.Extensions.Validation.Fluent/Uno.Extensions.Validation.Fluent.csproj
> +
```suggestion
```

We must document new stuff :)

2022-12-12 15:42 UTC, dr1rrb commented on src/Uno.Extensions.Validation/Uno.Extensions.Validation.csproj
> +		<WarningsNotAsErrors>$(WarningsNotAsErrors);CS1591</WarningsNotAsErrors>
```suggestion
```

2022-12-12 15:42 UTC, dr1rrb commented on src/Uno.Extensions.Validation.Fluent/Uno.Extensions.Validation.Fluent.csproj
> +		<UnoExtensionsGeneration_DisableModuleInitializerAttribute>True</UnoExtensionsGeneration_DisableModuleInitializerAttribute>
```suggestion
		<!-- As we are InternalsVisibleTo, we disable some compatibility types that are not used by package itself. -->
		<UnoExtensionsGeneration_DisableModuleInitializerAttribute>True</UnoExtensionsGeneration_DisableModuleInitializerAttribute>
```

You should be able to remove this also. Insteed we should remove the `InternalsVisibleTo` if needed.

2022-12-12 15:42 UTC, dr1rrb commented on src/Uno.Extensions.Validation/Uno.Extensions.Validation.csproj
> +		<UnoExtensionsGeneration_DisableModuleInitializerAttribute>True</UnoExtensionsGeneration_DisableModuleInitializerAttribute>
```suggestion

		<!-- As we are InternalsVisibleTo, we disable some compatibility types that are not used by package itself. -->
		<UnoExtensionsGeneration_DisableModuleInitializerAttribute>True</UnoExtensionsGeneration_DisableModuleInitializerAttribute>
```

Same here, you should be able to remove this.

2022-12-20 07:17 UTC, closed without merging

2022-12-20 07:17 UTC, nickrandolph commented
Replaced by https://github.com/unoplatform/uno.extensions/pull/1011